---

- hosts: all
  become: true
  tasks:

   - name: install updates (CentOS)
     dnf:
       update_only: yes
       update_cahce: yes
     when: ansible_distribution == "CentOS"

   - name: install updates(Ubuntu)
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

   - name: install apache and php package for Ubuntu Servers
     package:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"

   - name: install apache and php package for CentOSu Servers
     package:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "CentOS"


- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package (CentOS)
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      package:
        name: samba
        state: latest
