- name: install apache and php package for Ubuntu Servers
  tags: apache,apache2,ubuntu
  package:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache and php package for CentOSu Servers
  tags: apache,centos,httpd
  package:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644     
